### PR TITLE
Sublime 3 + extra search feature support

### PR DESCRIPTION
**Pull request by Stibbons**
Fix for sublime 3
+ allow new spec to link unit test with file: prefix and suffix (ex: file is named "foo.py" and its unit test is in "tests/test_foo.py"

### CODE REVIEW

**Comment by papaDoc** [comment]
Hi, 

Thanks for the patch.  I will look at it when I will  be back home. 

On February 24, 2015 5:32:42 PM EST, Gaetan Semet <notifications@github.com> wrote:
>Fix for sublime 3
>+ allow new spec to link unit test with file: prefix and suffix (ex:
>file is named "foo.py" and its unit test is in "tests/test_foo.py"
>You can view, comment on, or merge this pull request online at:
>
>  https://github.com/papaDoc/FastSwitch/pull/4
>
>-- Commit Summary --
>
>  * pep8 fix
>  * remove broken code
>  * Remove useless 'global' statement
>  * Rework to handle extended syntax
>  * tab
>  * remove trailing spaces
>
>-- File Changes --
>
>    M Default.sublime-keymap (4)
>    M FastSwitch.sublime-settings (52)
>    M README.md (154)
>    M fast_switch.py (369)
>
>-- Patch Links --
>
>https://github.com/papaDoc/FastSwitch/pull/4.patch
>https://github.com/papaDoc/FastSwitch/pull/4.diff
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/papaDoc/FastSwitch/pull/4

-- 
Sent from my Android phone with K-9 Mail. Please excuse my brevity.

**Comment by Stibbons** [comment]
I have reworked the main loop so I may have broken some cases... maybe we need some unit tests :)

**Comment by papaDoc** [comment]
Hi,

I'm back from vacations. 

I looked at your pull and the tests don't pass. 
It looks like the current directory of the file is not removed from the base.

This is the run for test1 with verbosity set to 99
FastSwitch 0.1: run: Start
FastSwitch 0.1: Settings: all: <sublime.Settings object at 0x7fd65d3cb890>
FastSwitch 0.1: syntax_name: start
FastSwitch 0.1: syntax_name: C++
FastSwitch 0.1: Syntax: C++
FastSwitch 0.1: Using settings for syntax C++: [[['.cpp'], ['src']], [['hpp'], ['.']]]
FastSwitch 0.1: Current active file: /home/ricard/Programmation/Python/FastSwitch/tests/Test_1/src/test1.cpp
FastSwitch 0.1: Base: /home/ricard/Programmation/Python/FastSwitch/tests/Test_1/src, filename: test1.cpp
FastSwitch 0.1: Checking if file "test1.cpp" has extension ".cpp" 
FastSwitch 0.1: "test1.cpp" has extension ".cpp" 
FastSwitch 0.1: Removing prefix ''
FastSwitch 0.1: => Looking for file "test1" with one of the following prefixes [''], one of the following extensions ['hpp'], in one of the sub directory ['.'], from the path "/home/ricard/Programmation/Python/FastSwitch/tests/Test_1/src"
FastSwitch 0.1: Investigating wife directory: "."
FastSwitch 0.1: The investigation directory with everything replaced: "."
wife_ext hpp
FastSwitch 0.1: Investigating for file "test1" in directory "/home/ricard/Programmation/Python/FastSwitch/tests/Test_1/src/." with extension "hpp"   <==== Here the src should have been removed
FastSwitch 0.1: Looking for wife file: /home/ricard/Programmation/Python/FastSwitch/tests/Test_1/src/./test1hpp
FastSwitch 0.1: Checking if file "test1.cpp" has extension "hpp" 
FastSwitch 0.1: The file [test1.cpp] has no extension found in the list ['.cpp'], ['hpp'] for the syntax [C++].

I added and comitted the test files this will help you debug.

I have a last comment.
It looks strange to me to have a "[]" 
"Python": [
            [ ["test_", "test"], ["py"], [".", ".."], [] ],
            [ [], ["py"], [".", "test", "tests"], ["test_", "test"] ]
          ]

Maybe we could have something like the following for the settings:
"Python": [
            [ ["py"], [".", ".."],  {prefix_to_remove: ["test_", "test"]}, {prefix_to_add: [] ],
            [ ["py"], [".", "test", "tests"], {prefix_to_remove: []}, {prefix_to_add: ["test_", "test"] ]
          ]

**Comment by papaDoc** [comment]
Hi,

I merged the commit 3474243

papaDoc

**Comment by Stibbons** [comment]
Thank! But the Work is not finished, there are regression when using @. I also want to add unit test for the "extended" syntax. Plus I also wanted to take your suggestion and have the configuration more verbose. This will arrive soon...  :)

**Comment by papaDoc** [comment]
Ok,
I will wait.

**Comment by Stibbons** [comment]
ok I have reworked my patch. I have added many unit test, just launch them with python lib/fastswitch.py to test all configuration.

I have switched to a completely different approach:
- settings are verbose, and in a new key named "extended"
- a setting can cover one or several syntax (I had to duplicate the same setting twice to switch between an html and js file)
- I have rewritten the search mecanism in a new function specifically dedidated to this new method. Maintaining both algorithm in the same method is not a good idea.
- two unit tests are broken: test3_HdrInPackageDir2 and test4_SrcHdrInComplexPackageDir, but I don't have many time to dig with this
- works great on linux, I need to check tonight how it behaves under windows

**Comment by papaDoc** [comment]
Hi,

I will take a look at it over the weekend.

**Comment by Stibbons** [comment]
Another rework: …
- support n transition (can loop on 3 files!!!)
- the according unit test covers it
- fix \ mess in windows (windows 7 64 bits)
:)

**Comment by papaDoc** [comment]
Salut Gaetan,

I took a look at the code and the problem was in the setup of the unittest. (Take a look at my new branch).

The new prefix stuff is great.  I already see some use to  it for myself. 
I also like the possibility to cycle between 3 or N files.

But you don't use the possibility to replace some directories in the directory structure (as with the @-2). 

It is also hard to understand the setting since you can have the old stuff and the new. I think they should be merged.
Something like:
"C++": [
              [ [ "ext_1" ], ["dir1", "dir2"], [ "prefix_1"] ],
              [ [ {extension: ["wife_ext_1", "wife_ext_2"] } ], ["wife_dir1"], ["wife_prefix"] ],
              [ ["affair_ext_1"], ["affair_ext1"], [ { "prefix": ["affair_prefix_1", affair_prefix_2"]} ]
      ]

The description (dictionary world) can be optional. This will be back compatible and you can cycle between the 3 or even more

**Comment by Stibbons** [comment]
If you look at test7_ExtendedSyntax_WithPrefixForTest1 unit test, it uses two syntaxes for a single setting. With the current way settings are organised, you have to completely duplicate the block to set it to both syntaxes "HTML" and "JS". I think you need to switch a new syntax. Keeping old one is for compatibility sake.

**Comment by papaDoc** [comment]
Hi,
I'm trying to merge your change with the original code and not use an separate list of settings.
Everything look good up to now. I'm almost complete need to verify one more time.

The changes are in my branch STibbons-master

**Comment by Stibbons** [comment]
Hello. Look great. I see some unit test that fails:

  test1_SrcHdrInSameDir1 (__main__.TestFastSwitch) ... ok
  test1_SrcHdrInSameDir2 (__main__.TestFastSwitch) ... ok
  test1_husband_extended_1 (__main__.TestFastSwitch) ... ok
  test1_husband_extended_2 (__main__.TestFastSwitch) ... ok
  test1_husband_extended_dict_1 (__main__.TestFastSwitch) ... ok
  test2_SrcHdrInTwoSibblingDirs1 (__main__.TestFastSwitch) ... ok
  test2_SrcHdrInTwoSibblingDirs2 (__main__.TestFastSwitch) ... ok
  test3_HdrInPackageDir1 (__main__.TestFastSwitch) ... ok
  test3_HdrInPackageDir2 (__main__.TestFastSwitch) ... ok
  test4_SrcHdrInComplexPackageDir1 (__main__.TestFastSwitch) ... ok
  test4_SrcHdrInComplexPackageDir2 (__main__.TestFastSwitch) ... ok
  test5_HdrInPublicJs1 (__main__.TestFastSwitch) ... ok
  test5_HdrInPublicJs2 (__main__.TestFastSwitch) ... ok
  test6_CppWithTestDir_settingInverted1 (__main__.TestFastSwitch) ... FAIL
  test6_CppWithTestDir_settingsInverted2 (__main__.TestFastSwitch) ... FAIL
  test6_ExtendedSyntax_WithPrefixForTest1 (__main__.TestFastSwitch) ... FAIL
  test6_ExtendedSyntax_WithPrefixForTest2 (__main__.TestFastSwitch) ... FAIL
  test7_ExtendedSyntax_WithPrefixForTest1 (__main__.TestFastSwitch) ... FAIL
  test7_ExtendedSyntax_WithPrefixForTest2 (__main__.TestFastSwitch) ... FAIL
  test7_ExtendedSyntax_WithPrefixForTest3 (__main__.TestFastSwitch) ... FAIL
  test8_ExtendedSyntax_SrcHdrInComplexPackageDir1 (__main__.TestFastSwitch) ... ok
  test8_ExtendedSyntax_SrcHdrInComplexPackageDir2 (__main__.TestFastSwitch) ... ok

So for me if you manage to have all use case working
(the only limitation I see is that to support the same config for HTML and JavaScript syntaxes, you
need to duplicate the block twice)

**Comment by papaDoc** [comment]
Hi,

The fails were du because I renamed some of the test files.

**Comment by papaDoc** [comment]
Salut Gaetan,

I finally was able to finish the change. 
All the unittests pass and the documentation was updated.

If you see something strange or if you want to add something to the documentation let me know. (My first language is not English so any typo syntax error is also welcome).

I will wait for your feedback and then I will merge it to the main branch.

Remi

**Comment by Stibbons** [comment]
Look good to me :)

**Pull request merged**
